insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (1, 1, 'el amor de Dios', '10/06/2021', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (2, 2, 'la virgen maria', '21/11/2019', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (3, 3, 'sagrada familia', '19/02/2020', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (4, 4, 'salmos', '22/03/2020', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (5, 5, 'el amor de Dios', '05/12/2019', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (6, 6, 'el cristianismo', '14/10/2019', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (7, 7, 'santos', '08/02/2020', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (8, 8, 'el padre nuestro', '27/12/2019', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (9, 9, 'salmos', '20/10/2019', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (10, 10, 'santos', '01/08/2019', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (11, 11, 'el espiritu santo', '29/11/2019', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (12, 12, 'arcangeles', '03/01/2019', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (13, 1, 'santos', '13/05/2020', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (14, 2, 'el espiritu santo', '15/09/2020', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (15, 3, 'sacramentos', '11/01/2021', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (16, 4, 'rezos', '20/01/2020', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (17, 5, 'la virgen maria', '05/10/2019', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (18, 6, 'santos', '15/06/2019', 'leccion escrita', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (19, 7, 'la ley de moises', '08/01/2021', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (20, 8, 'mandamientos', '06/09/2020', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (21, 9, 'el cristianismo', '02/11/2020', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (22, 10, 'apostoles', '14/03/2019', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (23, 11, 'las virtudes', '08/04/2020', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (24, 12, 'sagrada familia', '03/08/2020', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (25, 1, 'apostoles', '25/06/2020', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (26, 2, 'el credo', '11/09/2019', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (27, 3, 'el padre nuestro', '08/07/2019', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (28, 4, 'el amor de Dios', '26/01/2021', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (29, 5, 'arcangeles', '27/03/2021', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (30, 6, 'rezos', '16/01/2021', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (31, 7, 'la fe', '29/02/2020', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (32, 8, 'la ley de moises', '19/11/2020', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (33, 9, 'el espiritu santo', '21/03/2020', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (34, 10, 'santos', '27/01/2021', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (35, 11, 'el cristianismo', '25/08/2019', 'leccion escrita', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (36, 12, 'la vida de jesus', '21/01/2020', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (37, 1, 'sacramentos', '11/11/2019', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (38, 2, 'las virtudes', '25/08/2019', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (39, 3, 'el padre nuestro', '08/03/2020', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (40, 4, 'el ave maria', '22/02/2021', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (41, 5, 'la iglesia', '19/03/2021', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (42, 6, 'rezos', '16/03/2021', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (43, 7, 'rezos', '10/01/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (44, 8, 'la iglesia', '01/12/2019', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (45, 9, 'la fe', '19/03/2021', 'leccion escrita', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (46, 10, 'rezos', '01/07/2020', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (47, 11, 'la fe', '20/09/2019', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (48, 12, 'sagrada familia', '26/10/2020', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (49, 1, 'mandamientos', '29/04/2021', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (50, 2, 'las virtudes', '08/08/2019', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (51, 3, 'la vida de jesus', '14/09/2019', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (52, 4, 'sagrada familia', '25/02/2020', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (53, 5, 'sacramentos', '19/01/2019', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (54, 6, 'el ave maria', '03/05/2019', 'leccion escrita', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (55, 7, 'la iglesia', '19/03/2019', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (56, 8, 'el cristianismo', '14/10/2020', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (57, 9, 'el padre nuestro', '16/04/2020', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (58, 10, 'arcangeles', '25/08/2019', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (59, 11, 'la vida de jesus', '10/06/2021', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (60, 12, 'santos', '03/12/2019', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (61, 1, 'sagrada familia', '27/01/2020', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (62, 2, 'el padre nuestro', '04/07/2019', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (63, 3, 'rezos', '12/02/2020', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (64, 4, 'pecados capitales', '03/04/2020', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (65, 5, 'la fe', '20/11/2020', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (66, 6, 'la vida de jesus', '15/02/2020', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (67, 7, 'el espiritu santo', '11/01/2020', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (68, 8, 'los profetas', '04/04/2021', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (69, 9, 'el amor de Dios', '02/03/2021', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (70, 10, 'santos', '14/06/2021', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (71, 11, 'la virgen maria', '02/04/2020', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (72, 12, 'bienaventuranzas', '28/06/2020', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (73, 1, 'el amor de Dios', '15/08/2020', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (74, 2, 'los profetas', '01/01/2021', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (75, 3, 'la iglesia', '12/02/2020', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (76, 4, 'arcangeles', '03/08/2019', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (77, 5, 'bienaventuranzas', '27/03/2019', 'leccion escrita', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (78, 6, 'mandamientos', '10/07/2019', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (79, 7, 'arcangeles', '24/05/2021', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (80, 8, 'el credo', '26/10/2019', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (81, 9, 'mandamientos', '25/11/2019', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (82, 10, 'sacramentos', '16/09/2019', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (83, 11, 'arcangeles', '21/04/2021', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (84, 12, 'las virtudes', '11/04/2019', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (85, 1, 'arcangeles', '24/10/2019', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (86, 2, 'mandamientos', '31/07/2019', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (87, 3, 'la ley de moises', '17/12/2019', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (88, 4, 'salmos', '08/12/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (89, 5, 'salmos', '31/05/2020', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (90, 6, 'el ave maria', '18/09/2020', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (91, 7, 'bienaventuranzas', '14/08/2019', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (92, 8, 'el cristianismo', '25/02/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (93, 9, 'la vida de jesus', '13/06/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (94, 10, 'el amor de Dios', '03/02/2021', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (95, 11, 'pecados capitales', '30/05/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (96, 12, 'la virgen maria', '30/01/2019', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (97, 1, 'las virtudes', '03/07/2019', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (98, 2, 'la ley de moises', '06/07/2019', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (99, 3, 'el espiritu santo', '17/04/2020', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (100, 4, 'rezos', '22/06/2020', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (101, 5, 'las virtudes', '27/09/2020', 'leccion escrita', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (102, 6, 'el espiritu santo', '12/10/2020', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (103, 7, 'el padre nuestro', '21/04/2021', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (104, 8, 'la vida de jesus', '24/01/2021', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (105, 9, 'el cristianismo', '17/05/2019', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (106, 10, 'rezos', '12/06/2019', 'leccion escrita', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (107, 11, 'apostoles', '24/07/2020', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (108, 12, 'la fe', '23/12/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (109, 1, 'las virtudes', '13/03/2020', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (110, 2, 'sacramentos', '21/03/2021', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (111, 3, 'bienaventuranzas', '24/12/2019', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (112, 4, 'sagrada familia', '10/01/2020', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (113, 5, 'salmos', '12/04/2020', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (114, 6, 'rezos', '29/09/2020', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (115, 7, 'los profetas', '02/04/2020', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (116, 8, 'el amor de Dios', '24/11/2020', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (117, 9, 'mandamientos', '21/07/2019', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (118, 10, 'el ave maria', '01/06/2020', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (119, 11, 'la fe', '13/01/2021', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (120, 12, 'el ave maria', '17/06/2019', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (121, 1, 'los profetas', '02/03/2020', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (122, 2, 'salmos', '19/01/2021', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (123, 3, 'la ley de moises', '20/03/2020', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (124, 4, 'mandamientos', '30/01/2021', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (125, 5, 'la ley de moises', '16/02/2021', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (126, 6, 'el ave maria', '15/09/2019', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (127, 7, 'apostoles', '27/12/2020', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (128, 8, 'arcangeles', '11/09/2020', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (129, 9, 'bienaventuranzas', '01/12/2019', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (130, 10, 'la fe', '17/04/2020', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (131, 11, 'el cristianismo', '16/12/2019', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (132, 12, 'los profetas', '21/03/2019', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (133, 1, 'el espiritu santo', '21/03/2019', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (134, 2, 'apostoles', '06/07/2019', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (135, 3, 'bienaventuranzas', '25/09/2020', 'leccion escrita', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (136, 4, 'la virgen maria', '23/10/2019', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (137, 5, 'sagrada familia', '05/03/2020', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (138, 6, 'la virgen maria', '15/02/2021', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (139, 7, 'el espiritu santo', '24/07/2019', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (140, 8, 'la iglesia', '06/02/2019', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (141, 9, 'los profetas', '05/11/2020', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (142, 10, 'el cristianismo', '30/03/2021', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (143, 11, 'mandamientos', '22/03/2019', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (144, 12, 'el ave maria', '03/11/2020', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (145, 1, 'la vida de jesus', '18/10/2019', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (146, 2, 'sacramentos', '17/02/2019', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (147, 3, 'la vida de jesus', '26/09/2020', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (148, 4, 'pecados capitales', '06/03/2020', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (149, 5, 'la virgen maria', '20/03/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (150, 6, 'las virtudes', '12/04/2020', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (151, 7, 'el credo', '07/06/2019', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (152, 8, 'el padre nuestro', '21/04/2021', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (153, 9, 'la iglesia', '07/03/2021', 'leccion escrita', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (154, 10, 'el amor de Dios', '20/08/2019', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (155, 11, 'la fe', '11/07/2020', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (156, 12, 'pecados capitales', '05/06/2020', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (157, 1, 'salmos', '14/08/2019', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (158, 2, 'sacramentos', '15/02/2020', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (159, 3, 'el credo', '02/10/2020', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (160, 4, 'la ley de moises', '14/11/2020', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (161, 5, 'la iglesia', '22/12/2019', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (162, 6, 'sagrada familia', '31/05/2019', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (163, 7, 'santos', '30/05/2021', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (164, 8, 'el credo', '10/04/2021', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (165, 9, 'apostoles', '16/05/2019', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (166, 10, 'sacramentos', '31/05/2019', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (167, 11, 'los profetas', '13/02/2019', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (168, 12, 'pecados capitales', '05/12/2020', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (169, 1, 'la fe', '24/10/2020', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (170, 2, 'el espiritu santo', '20/06/2019', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (171, 3, 'la virgen maria', '12/05/2019', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (172, 4, 'la fe', '04/05/2021', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (173, 5, 'los profetas', '27/11/2020', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (174, 6, 'el ave maria', '20/08/2020', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (175, 7, 'sacramentos', '20/04/2021', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (176, 8, 'el ave maria', '24/05/2020', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (177, 9, 'la fe', '31/07/2019', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (178, 10, 'la iglesia', '26/01/2019', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (179, 11, 'las virtudes', '09/07/2019', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (180, 12, 'sagrada familia', '08/05/2019', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (181, 1, 'apostoles', '01/04/2021', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (182, 2, 'el amor de Dios', '09/08/2020', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (183, 3, 'el amor de Dios', '27/01/2020', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (184, 4, 'bienaventuranzas', '07/11/2020', 'leccion escrita', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (185, 5, 'la virgen maria', '06/02/2021', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (186, 6, 'las virtudes', '04/10/2019', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (187, 7, 'el padre nuestro', '24/06/2020', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (188, 8, 'mandamientos', '10/06/2020', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (189, 9, 'el espiritu santo', '01/03/2020', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (190, 10, 'el credo', '12/07/2020', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (191, 11, 'el cristianismo', '09/02/2019', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (192, 12, 'la iglesia', '21/10/2020', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (193, 1, 'la iglesia', '18/06/2019', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (194, 2, 'salmos', '12/05/2020', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (195, 3, 'la fe', '15/05/2019', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (196, 4, 'mandamientos', '13/05/2021', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (197, 5, 'apostoles', '29/03/2019', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (198, 6, 'pecados capitales', '11/02/2020', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (199, 7, 'la ley de moises', '13/11/2019', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (200, 8, 'el credo', '27/04/2021', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (201, 9, 'el ave maria', '26/11/2019', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (202, 10, 'la fe', '04/08/2019', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (203, 11, 'sagrada familia', '27/07/2020', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (204, 12, 'las virtudes', '09/05/2020', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (205, 1, 'la iglesia', '01/01/2020', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (206, 2, 'santos', '13/05/2021', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (207, 3, 'apostoles', '12/02/2019', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (208, 4, 'pecados capitales', '11/03/2020', 'leccion escrita', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (209, 5, 'los profetas', '20/04/2021', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (210, 6, 'santos', '15/02/2019', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (211, 7, 'arcangeles', '04/09/2020', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (212, 8, 'la vida de jesus', '05/04/2021', 'leccion escrita', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (213, 9, 'arcangeles', '04/08/2019', 'leccion escrita', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (214, 10, 'sagrada familia', '12/01/2021', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (215, 11, 'los profetas', '19/03/2020', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (216, 12, 'los profetas', '01/06/2020', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (217, 1, 'la iglesia', '23/11/2020', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (218, 2, 'las virtudes', '17/05/2019', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (219, 3, 'santos', '13/09/2019', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (220, 4, 'santos', '19/12/2019', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (221, 5, 'mandamientos', '10/05/2020', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (222, 6, 'la fe', '02/01/2021', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (223, 7, 'apostoles', '14/09/2020', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (224, 8, 'el amor de Dios', '14/09/2019', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (225, 9, 'el cristianismo', '10/05/2020', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (226, 10, 'el credo', '16/07/2019', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (227, 11, 'rezos', '19/11/2019', 'leccion escrita', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (228, 12, 'apostoles', '17/12/2020', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (229, 1, 'el cristianismo', '05/07/2019', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (230, 2, 'santos', '30/04/2021', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (231, 3, 'sacramentos', '15/01/2019', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (232, 4, 'mandamientos', '13/07/2020', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (233, 5, 'sacramentos', '01/03/2020', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (234, 6, 'el padre nuestro', '14/09/2020', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (235, 7, 'salmos', '02/08/2020', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (236, 8, 'santos', '24/04/2019', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (237, 9, 'pecados capitales', '13/10/2020', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (238, 10, 'la vida de jesus', '08/06/2019', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (239, 11, 'los profetas', '06/02/2020', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (240, 12, 'los profetas', '23/04/2021', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (241, 1, 'bienaventuranzas', '30/12/2019', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (242, 2, 'los profetas', '21/11/2019', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (243, 3, 'la fe', '02/03/2021', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (244, 4, 'la vida de jesus', '29/04/2020', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (245, 5, 'arcangeles', '01/08/2020', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (246, 6, 'santos', '24/04/2021', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (247, 7, 'el amor de Dios', '18/12/2019', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (248, 8, 'la vida de jesus', '01/05/2019', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (249, 9, 'la fe', '09/08/2019', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (250, 10, 'la fe', '12/03/2019', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (251, 11, 'el cristianismo', '24/09/2020', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (252, 12, 'pecados capitales', '10/07/2020', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (253, 1, 'la vida de jesus', '08/06/2019', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (254, 2, 'mandamientos', '22/01/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (255, 3, 'el cristianismo', '21/05/2021', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (256, 4, 'pecados capitales', '27/05/2019', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (257, 5, 'la iglesia', '07/03/2020', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (258, 6, 'la ley de moises', '12/04/2019', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (259, 7, 'la virgen maria', '29/10/2020', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (260, 8, 'las virtudes', '01/09/2019', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (261, 9, 'pecados capitales', '04/04/2021', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (262, 10, 'pecados capitales', '07/01/2021', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (263, 11, 'la ley de moises', '31/01/2020', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (264, 12, 'la virgen maria', '07/09/2019', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (265, 1, 'el credo', '14/04/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (266, 2, 'salmos', '11/03/2021', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (267, 3, 'salmos', '28/03/2019', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (268, 4, 'apostoles', '27/04/2019', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (269, 5, 'sacramentos', '13/08/2020', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (270, 6, 'santos', '15/03/2021', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (271, 7, 'arcangeles', '03/05/2021', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (272, 8, 'santos', '25/05/2021', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (273, 9, 'la iglesia', '21/06/2020', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (274, 10, 'la virgen maria', '15/02/2021', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (275, 11, 'los profetas', '04/07/2020', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (276, 12, 'los profetas', '22/12/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (277, 1, 'la fe', '10/07/2020', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (278, 2, 'el amor de Dios', '08/02/2019', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (279, 3, 'la vida de jesus', '15/03/2019', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (280, 4, 'sagrada familia', '06/12/2019', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (281, 5, 'el ave maria', '23/07/2019', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (282, 6, 'la fe', '15/02/2020', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (283, 7, 'las virtudes', '23/02/2021', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (284, 8, 'santos', '19/08/2019', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (285, 9, 'el espiritu santo', '21/01/2019', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (286, 10, 'sagrada familia', '28/12/2020', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (287, 11, 'la vida de jesus', '25/11/2020', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (288, 12, 'la virgen maria', '13/04/2020', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (289, 1, 'pecados capitales', '10/05/2021', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (290, 2, 'rezos', '30/03/2020', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (291, 3, 'el cristianismo', '07/01/2020', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (292, 4, 'rezos', '21/02/2021', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (293, 5, 'la fe', '09/02/2019', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (294, 6, 'la vida de jesus', '10/07/2020', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (295, 7, 'arcangeles', '18/03/2021', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (296, 8, 'las virtudes', '05/02/2019', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (297, 9, 'el amor de Dios', '20/08/2019', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (298, 10, 'la vida de jesus', '05/02/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (299, 11, 'el espiritu santo', '18/11/2019', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (300, 12, 'santos', '15/05/2020', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (301, 1, 'salmos', '03/01/2020', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (302, 2, 'la fe', '20/05/2020', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (303, 3, 'los profetas', '25/08/2019', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (304, 4, 'la iglesia', '08/11/2019', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (305, 5, 'sacramentos', '20/04/2020', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (306, 6, 'los profetas', '09/12/2019', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (307, 7, 'el padre nuestro', '14/05/2021', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (308, 8, 'sagrada familia', '01/06/2019', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (309, 9, 'salmos', '02/05/2021', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (310, 10, 'mandamientos', '24/06/2020', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (311, 11, 'el amor de Dios', '16/09/2019', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (312, 12, 'sagrada familia', '26/04/2019', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (313, 1, 'santos', '12/01/2019', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (314, 2, 'el padre nuestro', '24/05/2020', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (315, 3, 'pecados capitales', '04/04/2019', 'leccion escrita', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (316, 4, 'bienaventuranzas', '19/09/2020', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (317, 5, 'salmos', '05/12/2020', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (318, 6, 'bienaventuranzas', '22/08/2020', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (319, 7, 'rezos', '09/02/2019', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (320, 8, 'rezos', '17/01/2020', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (321, 9, 'santos', '22/02/2020', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (322, 10, 'sagrada familia', '05/02/2019', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (323, 11, 'salmos', '06/05/2020', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (324, 12, 'los profetas', '16/03/2020', 'leccion escrita', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (325, 1, 'salmos', '05/02/2019', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (326, 2, 'apostoles', '07/08/2020', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (327, 3, 'la virgen maria', '07/01/2021', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (328, 4, 'las virtudes', '03/02/2020', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (329, 5, 'sagrada familia', '20/06/2020', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (330, 6, 'el cristianismo', '21/02/2019', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (331, 7, 'arcangeles', '13/06/2020', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (332, 8, 'el ave maria', '05/01/2019', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (333, 9, 'los profetas', '18/02/2020', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (334, 10, 'el cristianismo', '20/08/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (335, 11, 'el cristianismo', '11/01/2021', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (336, 12, 'el cristianismo', '08/02/2021', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (337, 1, 'arcangeles', '18/03/2020', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (338, 2, 'la fe', '26/11/2020', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (339, 3, 'sagrada familia', '20/06/2020', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (340, 4, 'el padre nuestro', '26/07/2019', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (341, 5, 'el ave maria', '07/06/2021', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (342, 6, 'las virtudes', '25/01/2021', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (343, 7, 'el espiritu santo', '07/06/2021', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (344, 8, 'sacramentos', '12/11/2020', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (345, 9, 'el cristianismo', '14/12/2020', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (346, 10, 'las virtudes', '29/11/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (347, 11, 'el padre nuestro', '16/02/2021', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (348, 12, 'el padre nuestro', '29/03/2019', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (349, 1, 'el padre nuestro', '17/11/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (350, 2, 'rezos', '12/03/2020', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (351, 3, 'la iglesia', '07/01/2019', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (352, 4, 'sagrada familia', '21/04/2019', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (353, 5, 'sagrada familia', '31/05/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (354, 6, 'las virtudes', '21/05/2021', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (355, 7, 'la vida de jesus', '03/06/2020', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (356, 8, 'la ley de moises', '16/01/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (357, 9, 'sacramentos', '02/03/2020', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (358, 10, 'la virgen maria', '19/03/2020', 'leccion escrita', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (359, 11, 'salmos', '29/04/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (360, 12, 'apostoles', '17/01/2019', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (361, 1, 'santos', '26/11/2019', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (362, 2, 'sacramentos', '15/08/2020', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (363, 3, 'apostoles', '20/01/2020', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (364, 4, 'apostoles', '20/01/2020', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (365, 5, 'las virtudes', '13/11/2020', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (366, 6, 'el cristianismo', '11/11/2020', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (367, 7, 'salmos', '03/02/2020', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (368, 8, 'sacramentos', '19/05/2020', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (369, 9, 'sacramentos', '12/02/2020', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (370, 10, 'el padre nuestro', '13/06/2020', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (371, 11, 'el credo', '22/03/2021', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (372, 12, 'el amor de Dios', '10/09/2019', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (373, 1, 'apostoles', '25/01/2020', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (374, 2, 'rezos', '01/02/2020', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (375, 3, 'el ave maria', '29/04/2021', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (376, 4, 'el ave maria', '02/01/2021', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (377, 5, 'la ley de moises', '20/09/2019', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (378, 6, 'el amor de Dios', '19/03/2019', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (379, 7, 'mandamientos', '08/02/2020', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (380, 8, 'la vida de jesus', '15/12/2019', 'leccion escrita', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (381, 9, 'el amor de Dios', '29/01/2020', 'leccion escrita', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (382, 10, 'apostoles', '22/12/2019', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (383, 11, 'el padre nuestro', '20/02/2021', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (384, 12, 'la virgen maria', '24/09/2019', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (385, 1, 'la iglesia', '09/03/2020', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (386, 2, 'las virtudes', '28/02/2020', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (387, 3, 'los profetas', '21/03/2019', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (388, 4, 'rezos', '15/04/2020', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (389, 5, 'las virtudes', '04/06/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (390, 6, 'arcangeles', '15/04/2019', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (391, 7, 'bienaventuranzas', '27/02/2021', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (392, 8, 'santos', '05/03/2020', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (393, 9, 'la fe', '15/09/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (394, 10, 'el cristianismo', '09/12/2020', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (395, 11, 'el espiritu santo', '16/02/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (396, 12, 'el ave maria', '20/09/2020', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (397, 1, 'salmos', '10/02/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (398, 2, 'sacramentos', '16/03/2020', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (399, 3, 'mandamientos', '08/11/2020', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (400, 4, 'salmos', '17/02/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (401, 5, 'la ley de moises', '29/04/2021', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (402, 6, 'el espiritu santo', '04/06/2021', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (403, 7, 'mandamientos', '08/11/2020', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (404, 8, 'la iglesia', '26/05/2020', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (405, 9, 'la fe', '12/04/2021', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (406, 10, 'santos', '24/02/2019', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (407, 11, 'la virgen maria', '08/09/2020', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (408, 12, 'la vida de jesus', '06/11/2019', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (409, 1, 'el ave maria', '15/07/2020', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (410, 2, 'santos', '07/08/2019', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (411, 3, 'mandamientos', '18/09/2020', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (412, 4, 'las virtudes', '24/02/2021', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (413, 5, 'mandamientos', '17/10/2020', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (414, 6, 'el amor de Dios', '13/09/2020', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (415, 7, 'pecados capitales', '25/06/2020', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (416, 8, 'el espiritu santo', '09/10/2019', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (417, 9, 'la virgen maria', '10/10/2019', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (418, 10, 'los profetas', '13/04/2020', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (419, 11, 'el credo', '31/01/2019', 'exposicion grupal', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (420, 12, 'los profetas', '19/03/2020', 'leccion oral', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (421, 1, 'el credo', '12/12/2020', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (422, 2, 'sagrada familia', '24/08/2020', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (423, 3, 'las virtudes', '05/06/2021', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (424, 4, 'sacramentos', '27/06/2019', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (425, 5, 'mandamientos', '04/10/2019', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (426, 6, 'mandamientos', '01/12/2019', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (427, 7, 'mandamientos', '01/05/2020', 'leccion escrita', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (428, 8, 'arcangeles', '05/09/2019', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (429, 9, 'rezos', '31/01/2020', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (430, 10, 'la vida de jesus', '06/09/2020', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (431, 11, 'la vida de jesus', '07/08/2020', 'actividad recreativa', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (432, 12, 'santos', '18/03/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (433, 1, 'la ley de moises', '16/01/2020', 'leccion escrita', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (434, 2, 'el amor de Dios', '05/03/2019', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (435, 3, 'santos', '17/02/2019', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (436, 4, 'el credo', '02/01/2020', 'explicacion teorica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (437, 5, 'salmos', '17/10/2020', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (438, 6, 'el cristianismo', '05/06/2021', 'leccion escrita', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (439, 7, 'el cristianismo', '07/08/2019', 'demostracion practica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (440, 8, 'el amor de Dios', '18/02/2020', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (441, 9, 'pecados capitales', '25/12/2020', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (442, 10, 'la vida de jesus', '02/02/2020', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (443, 11, 'rezos', '28/06/2019', 'actividad recreativa', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (444, 12, 'pecados capitales', '07/04/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (445, 1, 'el padre nuestro', '14/09/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (446, 2, 'el amor de Dios', '23/10/2019', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (447, 3, 'apostoles', '14/03/2021', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (448, 4, 'pecados capitales', '29/05/2021', 'demostracion practica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (449, 5, 'los profetas', '20/03/2021', 'demostracion practica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (450, 6, 'sagrada familia', '18/08/2020', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (451, 7, 'salmos', '03/03/2019', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (452, 8, 'el espiritu santo', '17/01/2020', 'leccion escrita', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (453, 9, 'apostoles', '18/12/2020', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (454, 10, 'la iglesia', '11/07/2020', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (455, 11, 'mandamientos', '30/01/2020', 'explicacion teorica', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (456, 12, 'apostoles', '05/02/2020', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (457, 1, 'el ave maria', '02/01/2021', 'leccion oral', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (458, 2, 'santos', '15/09/2019', 'exposicion grupal', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (459, 3, 'sagrada familia', '16/12/2020', 'leccion oral', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (460, 4, 'santos', '10/02/2021', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (461, 5, 'apostoles', '04/12/2020', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (462, 6, 'el padre nuestro', '16/06/2019', 'leccion escrita', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (463, 7, 'salmos', '05/10/2020', 'demostracion practica', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (464, 8, 'los profetas', '27/08/2020', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (465, 9, 'la iglesia', '06/05/2021', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (466, 10, 'la virgen maria', '30/03/2021', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (467, 11, 'el ave maria', '24/07/2020', 'leccion oral', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (468, 12, 'el credo', '15/03/2019', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (469, 1, 'la vida de jesus', '03/05/2021', 'exposicion grupal', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (470, 2, 'el credo', '28/02/2019', 'actividad recreativa', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (471, 3, 'el espiritu santo', '07/05/2020', 'explicacion teorica', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (472, 4, 'salmos', '08/02/2019', 'actividad recreativa', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (473, 5, 'sacramentos', '24/02/2019', 'leccion oral', 'se dejo tarea para la casa');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (474, 6, 'el padre nuestro', '06/05/2021', 'demostracion practica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (475, 7, 'la virgen maria', '05/01/2020', 'actividad recreativa', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (476, 8, 'el cristianismo', '07/04/2019', 'explicacion teorica', null);
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (477, 9, 'el amor de Dios', '28/09/2019', 'exposicion grupal', 'todos participaron');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (478, 10, 'el ave maria', '06/07/2019', 'explicacion teorica', 'los alumnos no muestran interes en la clase');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (479, 11, 'rezos', '22/05/2021', 'exposicion grupal', 'faltaron mas de 5 alumnos');
insert into clase (cla_id, cur_id, cla_tema, cla_fecha, cla_descripcion, cla_observacion) values (480, 12, 'la iglesia', '09/08/2020', 'demostracion practica', 'se dejo tarea para la casa');
