insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (1, 118, 'Codigo de Calificacion 1 - Estudiante 118', 6.62, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (2, 124, 'Codigo de Calificacion 2 - Estudiante 124', 7.88, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (3, 55, 'Codigo de Calificacion 3 - Estudiante 55', 6.76, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (4, 51, 'Codigo de Calificacion 4 - Estudiante 51', 9.32, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (5, 116, 'Codigo de Calificacion 5 - Estudiante 116', 5.95, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (6, 64, 'Codigo de Calificacion 6 - Estudiante 64', 9.54, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (7, 99, 'Codigo de Calificacion 7 - Estudiante 99', 9.48, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (8, 108, 'Codigo de Calificacion 8 - Estudiante 108', 8.37, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (9, 24, 'Codigo de Calificacion 9 - Estudiante 24', 5.43, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (10, 56, 'Codigo de Calificacion 10 - Estudiante 56', 5.21, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (11, 128, 'Codigo de Calificacion 11 - Estudiante 128', 5.11, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (12, 107, 'Codigo de Calificacion 12 - Estudiante 107', 7.23, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (13, 138, 'Codigo de Calificacion 13 - Estudiante 138', 9.67, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (14, 140, 'Codigo de Calificacion 14 - Estudiante 140', 5.27, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (15, 150, 'Codigo de Calificacion 15 - Estudiante 150', 7.26, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (16, 82, 'Codigo de Calificacion 16 - Estudiante 82', 9.06, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (17, 71, 'Codigo de Calificacion 17 - Estudiante 71', 7.22, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (18, 137, 'Codigo de Calificacion 18 - Estudiante 137', 9.88, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (19, 109, 'Codigo de Calificacion 19 - Estudiante 109', 8.48, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (20, 27, 'Codigo de Calificacion 20 - Estudiante 27', 6.58, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (21, 87, 'Codigo de Calificacion 21 - Estudiante 87', 8.03, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (22, 86, 'Codigo de Calificacion 22 - Estudiante 86', 9.7, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (23, 131, 'Codigo de Calificacion 23 - Estudiante 131', 8.09, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (24, 76, 'Codigo de Calificacion 24 - Estudiante 76', 7.2, 'necesita repasar');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (25, 123, 'Codigo de Calificacion 25 - Estudiante 123', 9.89, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (26, 118, 'Codigo de Calificacion 26 - Estudiante 118', 5.19, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (27, 45, 'Codigo de Calificacion 27 - Estudiante 45', 7.57, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (28, 111, 'Codigo de Calificacion 28 - Estudiante 111', 5.51, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (29, 121, 'Codigo de Calificacion 29 - Estudiante 121', 8.73, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (30, 91, 'Codigo de Calificacion 30 - Estudiante 91', 5.66, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (31, 74, 'Codigo de Calificacion 31 - Estudiante 74', 5.46, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (32, 42, 'Codigo de Calificacion 32 - Estudiante 42', 8.97, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (33, 88, 'Codigo de Calificacion 33 - Estudiante 88', 7.86, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (34, 114, 'Codigo de Calificacion 34 - Estudiante 114', 5.77, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (35, 149, 'Codigo de Calificacion 35 - Estudiante 149', 8.1, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (36, 91, 'Codigo de Calificacion 36 - Estudiante 91', 8.99, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (37, 116, 'Codigo de Calificacion 37 - Estudiante 116', 5.89, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (38, 136, 'Codigo de Calificacion 38 - Estudiante 136', 6.25, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (39, 30, 'Codigo de Calificacion 39 - Estudiante 30', 5.76, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (40, 147, 'Codigo de Calificacion 40 - Estudiante 147', 8.22, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (41, 42, 'Codigo de Calificacion 41 - Estudiante 42', 6.38, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (42, 30, 'Codigo de Calificacion 42 - Estudiante 30', 7.25, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (43, 10, 'Codigo de Calificacion 43 - Estudiante 10', 6.74, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (44, 8, 'Codigo de Calificacion 44 - Estudiante 8', 8.96, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (45, 121, 'Codigo de Calificacion 45 - Estudiante 121', 7.97, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (46, 48, 'Codigo de Calificacion 46 - Estudiante 48', 6.47, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (47, 50, 'Codigo de Calificacion 47 - Estudiante 50', 5.64, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (48, 22, 'Codigo de Calificacion 48 - Estudiante 22', 9.11, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (49, 86, 'Codigo de Calificacion 49 - Estudiante 86', 9.22, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (50, 51, 'Codigo de Calificacion 50 - Estudiante 51', 5.4, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (51, 16, 'Codigo de Calificacion 51 - Estudiante 16', 5.93, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (52, 90, 'Codigo de Calificacion 52 - Estudiante 90', 8.59, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (53, 128, 'Codigo de Calificacion 53 - Estudiante 128', 8.77, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (54, 30, 'Codigo de Calificacion 54 - Estudiante 30', 8.51, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (55, 23, 'Codigo de Calificacion 55 - Estudiante 23', 6.59, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (56, 50, 'Codigo de Calificacion 56 - Estudiante 50', 9.23, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (57, 24, 'Codigo de Calificacion 57 - Estudiante 24', 9.37, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (58, 141, 'Codigo de Calificacion 58 - Estudiante 141', 6.85, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (59, 42, 'Codigo de Calificacion 59 - Estudiante 42', 6.39, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (60, 58, 'Codigo de Calificacion 60 - Estudiante 58', 8.85, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (61, 20, 'Codigo de Calificacion 61 - Estudiante 20', 6.57, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (62, 80, 'Codigo de Calificacion 62 - Estudiante 80', 7.67, 'necesita repasar');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (63, 44, 'Codigo de Calificacion 63 - Estudiante 44', 5.84, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (64, 146, 'Codigo de Calificacion 64 - Estudiante 146', 5.21, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (65, 85, 'Codigo de Calificacion 65 - Estudiante 85', 8.31, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (66, 97, 'Codigo de Calificacion 66 - Estudiante 97', 5.51, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (67, 140, 'Codigo de Calificacion 67 - Estudiante 140', 9.98, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (68, 9, 'Codigo de Calificacion 68 - Estudiante 9', 8.1, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (69, 28, 'Codigo de Calificacion 69 - Estudiante 28', 5.91, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (70, 19, 'Codigo de Calificacion 70 - Estudiante 19', 8.04, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (71, 96, 'Codigo de Calificacion 71 - Estudiante 96', 6.74, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (72, 65, 'Codigo de Calificacion 72 - Estudiante 65', 7.91, 'necesita repasar');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (73, 32, 'Codigo de Calificacion 73 - Estudiante 32', 8.29, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (74, 144, 'Codigo de Calificacion 74 - Estudiante 144', 8.2, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (75, 116, 'Codigo de Calificacion 75 - Estudiante 116', 9.54, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (76, 63, 'Codigo de Calificacion 76 - Estudiante 63', 9.47, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (77, 75, 'Codigo de Calificacion 77 - Estudiante 75', 6.39, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (78, 65, 'Codigo de Calificacion 78 - Estudiante 65', 7.3, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (79, 144, 'Codigo de Calificacion 79 - Estudiante 144', 6.94, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (80, 78, 'Codigo de Calificacion 80 - Estudiante 78', 7.64, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (81, 134, 'Codigo de Calificacion 81 - Estudiante 134', 7.03, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (82, 140, 'Codigo de Calificacion 82 - Estudiante 140', 7.23, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (83, 32, 'Codigo de Calificacion 83 - Estudiante 32', 9.02, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (84, 128, 'Codigo de Calificacion 84 - Estudiante 128', 6.2, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (85, 121, 'Codigo de Calificacion 85 - Estudiante 121', 7.75, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (86, 97, 'Codigo de Calificacion 86 - Estudiante 97', 6.29, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (87, 105, 'Codigo de Calificacion 87 - Estudiante 105', 8.95, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (88, 104, 'Codigo de Calificacion 88 - Estudiante 104', 7.01, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (89, 77, 'Codigo de Calificacion 89 - Estudiante 77', 8.17, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (90, 83, 'Codigo de Calificacion 90 - Estudiante 83', 8.73, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (91, 27, 'Codigo de Calificacion 91 - Estudiante 27', 6.62, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (92, 8, 'Codigo de Calificacion 92 - Estudiante 8', 7.4, 'necesita repasar');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (93, 91, 'Codigo de Calificacion 93 - Estudiante 91', 7.21, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (94, 72, 'Codigo de Calificacion 94 - Estudiante 72', 9.54, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (95, 25, 'Codigo de Calificacion 95 - Estudiante 25', 6.79, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (96, 61, 'Codigo de Calificacion 96 - Estudiante 61', 5.85, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (97, 20, 'Codigo de Calificacion 97 - Estudiante 20', 7.24, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (98, 68, 'Codigo de Calificacion 98 - Estudiante 68', 6.03, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (99, 96, 'Codigo de Calificacion 99 - Estudiante 96', 9.33, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (100, 31, 'Codigo de Calificacion 100 - Estudiante 31', 5.69, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (101, 67, 'Codigo de Calificacion 101 - Estudiante 67', 5.64, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (102, 24, 'Codigo de Calificacion 102 - Estudiante 24', 9.92, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (103, 86, 'Codigo de Calificacion 103 - Estudiante 86', 8.65, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (104, 42, 'Codigo de Calificacion 104 - Estudiante 42', 7.01, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (105, 23, 'Codigo de Calificacion 105 - Estudiante 23', 7.15, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (106, 64, 'Codigo de Calificacion 106 - Estudiante 64', 9.84, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (107, 117, 'Codigo de Calificacion 107 - Estudiante 117', 7.92, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (108, 27, 'Codigo de Calificacion 108 - Estudiante 27', 6.83, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (109, 40, 'Codigo de Calificacion 109 - Estudiante 40', 8.55, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (110, 96, 'Codigo de Calificacion 110 - Estudiante 96', 5.25, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (111, 136, 'Codigo de Calificacion 111 - Estudiante 136', 7.75, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (112, 18, 'Codigo de Calificacion 112 - Estudiante 18', 7.31, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (113, 59, 'Codigo de Calificacion 113 - Estudiante 59', 9.66, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (114, 53, 'Codigo de Calificacion 114 - Estudiante 53', 8.27, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (115, 89, 'Codigo de Calificacion 115 - Estudiante 89', 9.03, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (116, 69, 'Codigo de Calificacion 116 - Estudiante 69', 5.63, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (117, 113, 'Codigo de Calificacion 117 - Estudiante 113', 5.09, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (118, 29, 'Codigo de Calificacion 118 - Estudiante 29', 7.89, 'necesita repasar');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (119, 134, 'Codigo de Calificacion 119 - Estudiante 134', 6.75, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (120, 122, 'Codigo de Calificacion 120 - Estudiante 122', 8.86, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (121, 8, 'Codigo de Calificacion 121 - Estudiante 8', 5.32, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (122, 42, 'Codigo de Calificacion 122 - Estudiante 42', 9.42, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (123, 146, 'Codigo de Calificacion 123 - Estudiante 146', 7.64, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (124, 93, 'Codigo de Calificacion 124 - Estudiante 93', 6.24, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (125, 77, 'Codigo de Calificacion 125 - Estudiante 77', 7.39, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (126, 146, 'Codigo de Calificacion 126 - Estudiante 146', 7.64, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (127, 83, 'Codigo de Calificacion 127 - Estudiante 83', 8.01, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (128, 35, 'Codigo de Calificacion 128 - Estudiante 35', 8.16, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (129, 86, 'Codigo de Calificacion 129 - Estudiante 86', 5.59, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (130, 146, 'Codigo de Calificacion 130 - Estudiante 146', 9.11, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (131, 90, 'Codigo de Calificacion 131 - Estudiante 90', 9.44, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (132, 11, 'Codigo de Calificacion 132 - Estudiante 11', 9.23, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (133, 121, 'Codigo de Calificacion 133 - Estudiante 121', 6.89, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (134, 54, 'Codigo de Calificacion 134 - Estudiante 54', 7.22, 'necesita repasar');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (135, 66, 'Codigo de Calificacion 135 - Estudiante 66', 5.37, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (136, 79, 'Codigo de Calificacion 136 - Estudiante 79', 9.15, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (137, 80, 'Codigo de Calificacion 137 - Estudiante 80', 9.91, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (138, 101, 'Codigo de Calificacion 138 - Estudiante 101', 5.13, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (139, 58, 'Codigo de Calificacion 139 - Estudiante 58', 7.66, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (140, 35, 'Codigo de Calificacion 140 - Estudiante 35', 8.84, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (141, 47, 'Codigo de Calificacion 141 - Estudiante 47', 6.85, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (142, 34, 'Codigo de Calificacion 142 - Estudiante 34', 7.4, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (143, 73, 'Codigo de Calificacion 143 - Estudiante 73', 7.22, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (144, 14, 'Codigo de Calificacion 144 - Estudiante 14', 8.72, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (145, 79, 'Codigo de Calificacion 145 - Estudiante 79', 5.23, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (146, 40, 'Codigo de Calificacion 146 - Estudiante 40', 8.36, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (147, 53, 'Codigo de Calificacion 147 - Estudiante 53', 9.34, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (148, 114, 'Codigo de Calificacion 148 - Estudiante 114', 6.58, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (149, 59, 'Codigo de Calificacion 149 - Estudiante 59', 8.05, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (150, 16, 'Codigo de Calificacion 150 - Estudiante 16', 9.57, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (151, 81, 'Codigo de Calificacion 151 - Estudiante 81', 8.91, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (152, 148, 'Codigo de Calificacion 152 - Estudiante 148', 7.29, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (153, 43, 'Codigo de Calificacion 153 - Estudiante 43', 6.77, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (154, 48, 'Codigo de Calificacion 154 - Estudiante 48', 8.19, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (155, 148, 'Codigo de Calificacion 155 - Estudiante 148', 8.89, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (156, 24, 'Codigo de Calificacion 156 - Estudiante 24', 6.02, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (157, 101, 'Codigo de Calificacion 157 - Estudiante 101', 5.23, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (158, 87, 'Codigo de Calificacion 158 - Estudiante 87', 5.75, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (159, 54, 'Codigo de Calificacion 159 - Estudiante 54', 5.77, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (160, 47, 'Codigo de Calificacion 160 - Estudiante 47', 9.29, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (161, 148, 'Codigo de Calificacion 161 - Estudiante 148', 6.97, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (162, 60, 'Codigo de Calificacion 162 - Estudiante 60', 6.49, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (163, 10, 'Codigo de Calificacion 163 - Estudiante 10', 6.78, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (164, 47, 'Codigo de Calificacion 164 - Estudiante 47', 5.85, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (165, 61, 'Codigo de Calificacion 165 - Estudiante 61', 6.99, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (166, 7, 'Codigo de Calificacion 166 - Estudiante 7', 7.09, 'necesita repasar');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (167, 7, 'Codigo de Calificacion 167 - Estudiante 7', 8.59, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (168, 89, 'Codigo de Calificacion 168 - Estudiante 89', 5.68, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (169, 2, 'Codigo de Calificacion 169 - Estudiante 2', 9.68, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (170, 53, 'Codigo de Calificacion 170 - Estudiante 53', 7.74, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (171, 123, 'Codigo de Calificacion 171 - Estudiante 123', 8.95, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (172, 98, 'Codigo de Calificacion 172 - Estudiante 98', 7.34, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (173, 47, 'Codigo de Calificacion 173 - Estudiante 47', 9.3, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (174, 100, 'Codigo de Calificacion 174 - Estudiante 100', 8.51, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (175, 92, 'Codigo de Calificacion 175 - Estudiante 92', 6.35, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (176, 40, 'Codigo de Calificacion 176 - Estudiante 40', 9.51, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (177, 132, 'Codigo de Calificacion 177 - Estudiante 132', 7.5, 'necesita repasar');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (178, 84, 'Codigo de Calificacion 178 - Estudiante 84', 8.49, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (179, 88, 'Codigo de Calificacion 179 - Estudiante 88', 5.08, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (180, 79, 'Codigo de Calificacion 180 - Estudiante 79', 9.79, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (181, 89, 'Codigo de Calificacion 181 - Estudiante 89', 7.95, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (182, 40, 'Codigo de Calificacion 182 - Estudiante 40', 7.85, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (183, 24, 'Codigo de Calificacion 183 - Estudiante 24', 7.93, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (184, 141, 'Codigo de Calificacion 184 - Estudiante 141', 8.29, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (185, 147, 'Codigo de Calificacion 185 - Estudiante 147', 5.57, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (186, 113, 'Codigo de Calificacion 186 - Estudiante 113', 9.46, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (187, 12, 'Codigo de Calificacion 187 - Estudiante 12', 9.46, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (188, 107, 'Codigo de Calificacion 188 - Estudiante 107', 8.32, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (189, 23, 'Codigo de Calificacion 189 - Estudiante 23', 5.53, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (190, 65, 'Codigo de Calificacion 190 - Estudiante 65', 5.48, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (191, 76, 'Codigo de Calificacion 191 - Estudiante 76', 9.65, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (192, 70, 'Codigo de Calificacion 192 - Estudiante 70', 7.06, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (193, 22, 'Codigo de Calificacion 193 - Estudiante 22', 7.47, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (194, 90, 'Codigo de Calificacion 194 - Estudiante 90', 6.46, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (195, 150, 'Codigo de Calificacion 195 - Estudiante 150', 7.85, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (196, 32, 'Codigo de Calificacion 196 - Estudiante 32', 6.37, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (197, 2, 'Codigo de Calificacion 197 - Estudiante 2', 6.5, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (198, 81, 'Codigo de Calificacion 198 - Estudiante 81', 8.83, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (199, 131, 'Codigo de Calificacion 199 - Estudiante 131', 5.55, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (200, 67, 'Codigo de Calificacion 200 - Estudiante 67', 6.84, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (201, 3, 'Codigo de Calificacion 201 - Estudiante 3', 8.07, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (202, 29, 'Codigo de Calificacion 202 - Estudiante 29', 8.65, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (203, 107, 'Codigo de Calificacion 203 - Estudiante 107', 6.3, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (204, 134, 'Codigo de Calificacion 204 - Estudiante 134', 9.6, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (205, 94, 'Codigo de Calificacion 205 - Estudiante 94', 7.39, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (206, 50, 'Codigo de Calificacion 206 - Estudiante 50', 9.78, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (207, 12, 'Codigo de Calificacion 207 - Estudiante 12', 5.27, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (208, 4, 'Codigo de Calificacion 208 - Estudiante 4', 7.78, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (209, 20, 'Codigo de Calificacion 209 - Estudiante 20', 8.74, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (210, 138, 'Codigo de Calificacion 210 - Estudiante 138', 7.35, 'necesita repasar');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (211, 16, 'Codigo de Calificacion 211 - Estudiante 16', 5.14, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (212, 54, 'Codigo de Calificacion 212 - Estudiante 54', 8.27, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (213, 141, 'Codigo de Calificacion 213 - Estudiante 141', 6.99, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (214, 64, 'Codigo de Calificacion 214 - Estudiante 64', 9.5, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (215, 108, 'Codigo de Calificacion 215 - Estudiante 108', 8.85, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (216, 60, 'Codigo de Calificacion 216 - Estudiante 60', 7.24, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (217, 116, 'Codigo de Calificacion 217 - Estudiante 116', 9.05, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (218, 132, 'Codigo de Calificacion 218 - Estudiante 132', 8.51, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (219, 83, 'Codigo de Calificacion 219 - Estudiante 83', 7.53, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (220, 53, 'Codigo de Calificacion 220 - Estudiante 53', 7.37, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (221, 42, 'Codigo de Calificacion 221 - Estudiante 42', 7.97, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (222, 73, 'Codigo de Calificacion 222 - Estudiante 73', 5.45, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (223, 103, 'Codigo de Calificacion 223 - Estudiante 103', 7.87, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (224, 110, 'Codigo de Calificacion 224 - Estudiante 110', 9.45, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (225, 23, 'Codigo de Calificacion 225 - Estudiante 23', 8.77, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (226, 135, 'Codigo de Calificacion 226 - Estudiante 135', 8.54, 'sin observación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (227, 84, 'Codigo de Calificacion 227 - Estudiante 84', 7.06, 'necesita repasar');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (228, 81, 'Codigo de Calificacion 228 - Estudiante 81', 8.18, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (229, 57, 'Codigo de Calificacion 229 - Estudiante 57', 7.54, 'buen estudiante');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (230, 116, 'Codigo de Calificacion 230 - Estudiante 116', 5.99, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (231, 11, 'Codigo de Calificacion 231 - Estudiante 11', 6.21, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (232, 47, 'Codigo de Calificacion 232 - Estudiante 47', 6.11, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (233, 29, 'Codigo de Calificacion 233 - Estudiante 29', 5.08, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (234, 54, 'Codigo de Calificacion 234 - Estudiante 54', 9.18, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (235, 107, 'Codigo de Calificacion 235 - Estudiante 107', 8.23, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (236, 91, 'Codigo de Calificacion 236 - Estudiante 91', 6.05, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (237, 84, 'Codigo de Calificacion 237 - Estudiante 84', 8.92, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (238, 62, 'Codigo de Calificacion 238 - Estudiante 62', 8.56, 'Pasa de nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (239, 81, 'Codigo de Calificacion 239 - Estudiante 81', 5.99, 'pierde el nivel');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (240, 100, 'Codigo de Calificacion 240 - Estudiante 100', 6.65, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (241, 118, 'Codigo de Calificacion 241 - Estudiante 118', 7.66, 'necesita repasar');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (242, 13, 'Codigo de Calificacion 242 - Estudiante 13', 6.07, 'va a recuperación');
insert into calificacion (cal_id, al_id, cal_codigo, cal_nota_final, cal_observacion) values (243, 85, 'Codigo de Calificacion 243 - Estudiante 85', 5.62, 'pierde el nivel');
